#!/bin/bash 
#PBS -o logfile.log 
#PBS -e errorfile.err 
#PBS -l walltime=168:00:00 
#PBS -l select=1:ncpus=1

tpdir=`echo $PBS_JOBID | cut -f 1 -d .`
tempdir=$HOME/scratch/MPOL_$tpdir
mkdir -p $tempdir
cd $tempdir
cp -R $PBS_O_WORKDIR/* .

source /apps/intel/oneapi/setvars.sh
source /apps/intel/oneapi/mkl/latest/env/vars.sh

